services:
  - type: web
    name: traderxgboost
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install aiohttp
    startCommand: python render_sim.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: REPLAY_SPEED
        value: "30"
